### ISSUE TITLE
Missing hourly values; resolution is daily

### ISSUE THREAD

**Issue by mikeage** [GuyKh/iec-custom-component#106]
## System Information

version | core-2024.4.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.0-20-amd64
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4995
Installed Version | 1.34.0
Stage | running
Available Repositories | 1416
Downloaded Repositories | 25

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 14

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 14
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 27, 2024 at 9:26 PM
-- | --
current_recorder_run | April 28, 2024 at 3:59 PM
estimated_db_size | 641.55 MiB
database_engine | mysql
database_version | 10.11.7

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Based on #68 , I was expecting to get hourly data, but seems like I'm only getting daily logs.

<img width="1233" alt="Screenshot 2024-04-29 at 22 00 09" src="https://github.com/GuyKh/iec-custom-component/assets/87874/88278971-321a-41f6-aedd-3f7ad6ffbfd5">

I have a smart meter, and from the IEC site, I can request the CSV by mail with the 15 minute resolution (though I understand that this is not so reliable from the API, from #68).

### Reproduction steps

1. Add the integration
2. Wait
3. Graph the meter readings

### Debug logs

(just custom_components.iec and iec_api): https://termbin.com/lrc7

**Comment by GuyKh** [comment]
You're correct. Currently, the current consumption changes on a daily basis.

**Comment by mikeage** [comment]
Ok, as long as it's not me, I feel better. I just started using the extension a week ago, so I wasn't sure if it was an IEC change or if I set up something incorrectly.

Thanks for your work on this; even daily, I'm enjoying it a lot!

**Comment by GuyKh** [comment]
@mikeage - As far as I tested, the best case scenario for getting the relevant meter measurements is using `https://iecapi.iec.co.il//api/Consumption/RemoteReadingRange/{{contract_id}}` API.

However, even when trying to get data from Tomorrow 
(e.g. this is when I try to get from `2024-05-01`)
```
    "futureConsumptionInfo": {
        "lastInvoiceDate": null,
        "currentDate": "2024-04-30",
        "futureConsumption": null,
        "totalImport": 13223.17,
        "totalImportDate": "2024-04-30"
    },
```
It's still is being updated once a day (or at least in a while)... So... not sure if I can do it manually.

You can test yourself by using the Postman collections.

I'd appreciate also if you could sniff around in IEC site, and you could point me to a page where the "latest" value is shown and we'll try to backtrace the call there.
Also - check how often is this being updated.

**Comment by mikeage** [comment]
ok, having looked at this a bit more, and played around with the postman collection, I think I realize what my original question should have been. I was looking at the entity `sensor.iec_contract_FOO_meter_BAR_iec_latest_meter_reading` which, as you say, is only updated once per day in the API.

But in issue 68, you showed a graph of *incremental* usage, showing the kWh for each hour, and said that this was in the long term storage in HA. I didn't find that sensor; where did that data come from in that graph?

**Comment by GuyKh** [comment]
Yeah, I think that this is a bit of a misconception with HA, I think the naive approach is that "everything is a sensor" and you're expected to work your dashboards with sensors in mind, but there are more than that.

Anyway, I was happy to help

**Comment by mikeage** [comment]
I didn't even have `energy:` in my configuration.yml! (or `default_configuration:`). I've added it, now see an energy dashboard, but I don't see anything under the IEC domain. Do you know if I need to wait a day or two for this to be added to the statistics now? 
<img width="451" alt="Screenshot 2024-05-01 at 11 43 09" src="https://github.com/GuyKh/iec-custom-component/assets/87874/3798e7c5-b919-48f1-8e71-3941d79ccf09">

**Comment by mikeage** [comment]
(sorry for the basic questions; I've been using HA for several years, but this is my first foray into energy management, and things that aren't sensors and such ;-) )

**Comment by GuyKh** [comment]
@mikeage - you sure you have a SMART meter? 
Otherwise, the data is fetched from the invoice (once in one or two months)

**Comment by mikeage** [comment]
Yes; I have daily data in the sensor and hourly in the API calls, but I wonder if the lack of the `energy:` integration caused it not to load the initial data

**Comment by GuyKh** [comment]
I don't think so.
You can set the logs on `debug` (as described in the readme), you should see something like:
```
2024-05-01 11:47:04.430 DEBUG (MainThread) [custom_components.iec.coordinator] Last statistics are from 2024-04-30 23:00:00
2024-05-01 11:47:04.430 DEBUG (MainThread) [custom_components.iec.coordinator] The date to fetch is today or later, replacing it with Today at 01:00:00
2024-05-01 11:47:04.431 DEBUG (MainThread) [custom_components.iec.coordinator] Fetching consumption from 2024-05-01 01:00:00
2024-05-01 11:47:05.985 DEBUG (MainThread) [custom_components.iec.coordinator] LongTerm Statistics - Skipping 2024-05-01 00:00:00+03:00 since it's partial for the hour
```

etc.

**Comment by mikeage** [comment]
Can I ask you to take a look at https://termbin.com/k4u0; this is all of my iec logs from a recent reboot. 

I have:

```
2024-05-01 11:59:39.566 DEBUG (MainThread) [custom_components.iec.coordinator] Updating statistics for IEC Contract 341119390
2024-05-01 11:59:42.169 DEBUG (MainThread) [custom_components.iec.coordinator] Updating statistic for the first time
```

but that's it for grepping for "statistics"

**Comment by mikeage** [comment]
Maybe it's because of this line?

```
2024-05-01 11:59:43.637 DEBUG (MainThread) [custom_components.iec.coordinator] No recent usage data. Skipping update
```

It looks like it fetched:
```
b'{"meterSerialNumber":"23182212","meterCode":"67","lastInvoiceDate":"2024-04-03","fromDate":"2024-04-03","resolution":1}'
```
which is before I got my smart meter (April 8th).

**Comment by GuyKh** [comment]
:) 1 month ago was too optimistic?
I guess it worth trying in a few days and maybe it'll solve itself?

(or modify the coordinator.py yourself for a single run)

**Comment by mikeage** [comment]
Should I open a bug that weeks=4 isn't really a month ago? :-p

I changed it to 3 weeks, and now I see:

```
2024-05-01 12:34:48.332 DEBUG (MainThread) [custom_components.iec.coordinator] Fetching LongTerm Statistics since 2024-04-09 23:00:00+03:00
```

And I have the `iec:` domain in my energy dashboard :-)

It says up to 2 hours for data to appear, so I'll give it some time to process, etc.

**Comment by GuyKh** [comment]
You can revert your changes as something is already in the HA db.
But yeah, every hour it tries to fetch the next hour

**Comment by mikeage** [comment]
Perhaps this should be an issue, but I found a problem with the data that was being imported. For each day (advancing one day per hour), it was setting a value of 0 for each hour, even though it was getting data for every 15 minute period from the API.
 
 If I made this small change, it worked:
 
 ```diff
 diff --git a/custom_components/iec/coordinator.py b/custom_components/iec/coordinator.py
index ef59366..6366888 100644
--- a/custom_components/iec/coordinator.py
+++ b/custom_components/iec/coordinator.py
@@ -417,7 +417,8 @@ class IecApiCoordinator(DataUpdateCoordinator[dict[str, dict[str, Any]]]):
                 if key <= last_stat_req_hour:
                     _LOGGER.debug(f"LongTerm Statistics - Skipping {key} data since it's already reported")
                     continue
-                readings_by_hour[key] = sum(reading.value for reading in group)
+                readings_by_hour[key] = sum(reading.value for reading in group_list)
+

             consumption_metadata = StatisticMetaData(
                 has_mean=False,
```

Now I'm getting valid statistics for each hour of the day that it processes.

I'm not sure why; I thought you could iterate over a group. But I don't know a good way to test this; each time I restart HA, it advances one day, and I'm getting fairly close to today already (I don't know how to modify the long term statistics such that it thinks it needs to start again from Apr 8th -- if you can tell me, I'd be happy to do more investigation)

**Comment by GuyKh** [comment]
Thanks @mikeage - I actually did the exact opposite since I though group iteration should work. But I'll gladly restore that.

**Comment by mikeage** [comment]
I'll be honest; I thought it should work too! I'm not sure why it didn't...

**Comment by GuyKh** [comment]
Anyway, for future reference and ordered process - please open a separate ticket for that
