### ISSUE TITLE
Contracts show `no_contracts` during configuration flow

### ISSUE THREAD

**Issue by niruse** [GuyKh/iec-custom-component#118]
### System Health details

<img width="350" alt="image" src="https://github.com/GuyKh/iec-custom-component/assets/44327594/df6adda0-44f9-4148-b630-95a61335a178">

**Comment by GuyKh** [comment]
Waiting for logs

**Comment by GuyKh** [comment]
By looking deeper - issue is caused by a contract with status `2`, where as the current condition is `status=1`
https://github.com/GuyKh/iec-custom-component/blob/main/custom_components/iec/config_flow.py#L123
