### ISSUE TITLE
When users just installed meters, trying to fetch data from 1 month back would fail

### ISSUE THREAD

**Issue by GuyKh** [GuyKh/iec-custom-component#128]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When users just installed meters, trying to fetch data from 1 month back would fail since the data is more recent.

### Reproduction steps

1.Install a new smart_meter
2.install the component without a month passing
3.Check for `iec:` in energy dashboard
...

### Debug logs

```text
N/A
```

**Comment by GuyKh** [comment]
Per @maorcc report

**Comment by GuyKh** [comment]
One optional solution would be to have the **time to fetch if no recent statistics** to be customizable in the config_flow rather than hardcoded 4 weeks (https://github.com/GuyKh/iec-custom-component/blob/main/custom_components/iec/coordinator.py#L355)

**Comment by GuyKh** [comment]
Or, perhaps - `min(meter_installation_date, today-30days)` or something similar. 
I wasn't able to find the time when the meter was installed in IEC API so far.

**Comment by maorcc** [comment]
@GuyKh, do you have access to an account with a recently installed smart meter? Playing with the data received from such an account might give us a hint.

**Comment by GuyKh** [comment]
Nope

**Comment by GuyKh** [comment]
Welll.... actually - in `RemoteReadingRange` - one of the fields is `"meterStartDate": "2024-04-01"` Looks like a lead
