### ISSUE TITLE
Button to send a power consumption file to email

### ISSUE THREAD

**Issue by tzagim** [GuyKh/iec-custom-component#135]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Button to send an electricity consumption file by email, instead of entering the IEC website

### Describe the solution you'd like

```
https://iecapi.iec.co.il/api/Consumption/SendConsumptionReportToMail/{contract_id}
```

```json
{
    "emailAddress": "your@mail.com",
    "meterCode": "{{device_code}}",
    "meterSerial": "{{device_id}}"
}
```

### Describe alternatives you've considered

You need to think about whether to retrieve the email address from the IEC website, or enter it manually, or alternatively the Home Assistant email address.

### Additional context

I don't want to overload the previous discussion. (https://github.com/GuyKh/iec-custom-component/issues/132)

**Comment by GuyKh** [comment]
I guess you would want this as the part of https://github.com/GuyKh/py-iec-api/, not the component

**Comment by tzagim** [comment]
> I guess you would want this as the part of https://github.com/GuyKh/py-iec-api/, not the component

TNX
https://github.com/GuyKh/py-iec-api/issues/123
