### ISSUE TITLE
Error with Private Producers

### ISSUE THREAD

**Issue by GuyKh** [GuyKh/iec-custom-component#140]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 377, in _async_update_data
    last_meter_read = int(devices_by_id.counter_devices[0].last_mr)
                          ~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

### Reproduction steps

1. Start HA with private producers

### Debug logs

```text
When calling https://iecapi.iec.co.il/api/Device/{{contract_id}}/{{device_id}} with a private producer - you get:


{
    "data": {
        "counterDevices": null,
        "mrType": "00"
    },
    "reponseDescriptor": {
        "isSuccess": false,
        "code": "07",
        "description": "No authorization for this type of product: Private Producer"
    }
}
```

So you can't extract `last_meter_read`
```


### Diagnostics dump

_No response_

**Comment by sefininio** [comment]
@GuyKh 
I am happy to help with debugging this, let me know what you need :)

**Comment by GuyKh** [comment]
Sovled with #146
