### ISSUE TITLE
Incorrect sensor information

### ISSUE THREAD

**Issue by tzagim** [GuyKh/iec-custom-component#143]
### System Health details

None

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

@GuyKh 
I debugging in the new version.

The following sensors work fine for me:
1. this_month_electric_consumption
2. last_bill_date
3. iec_latest_meter_reading
4. last_bill_electric_usage_to_date
5. last_bill_meter_reading
6. last_bill_length_in_days
7. last_bill_electric_cost

The following sensors are working wrong for me:
1. yesterday_electric_consumption - it seems to me that because he ask for ```+ timedelta``` instead of ```- timedelta```. ```{"meterSerialNumber":"1234567","meterCode":"xxx","lastInvoiceDate":"2024-08-12","fromDate":"2024-08-12","resolution":3}``` returns incorrect information.
2. today_electric_consumption - because of the same problem, for me it only works if you ask for yesterday's date (maybe it's because I have a new counter, I don't know).

### Reproduction steps

None

### Debug logs

```text
None
```

**Comment by GuyKh** [comment]
Your source of truth should always be the data in IEC.
As they state, the data from Today and Yesterday may be inaccurate (and that's the reason you see what you see).
The fact that I'm using "tomorrow" - where I only use it to fetch "current reading" - is since it does indeed take the latest value

**Comment by tzagim** [comment]
@GuyKh 
I did debugging through friend IEC accounts, it turns out that the problem is in my meter, if the meter hasn't celebrated a month's birthday, it has a lot of trouble pulling up-to-date data.

And that explains all my recent errors.

sorry to bother you

PS. 
Maybe make the patch for ```meterStartDate - localized_today <= "30"```, because it helps to retrieve current + more recent data.

**Comment by GuyKh** [comment]
The issue here could be only when today is the last day of the month, but even then I only read the future consumption...

**Comment by tzagim** [comment]
I thought about it again, it seems to me that it makes no sense to disrupt everything for the new meter replacement, maybe put a warning if the meter has not celebrated its 30 day birthday that the data may not be accurate.

**Comment by GuyKh** [comment]
Wait @tzagim - are we talking only about recent meters?

I think that's an overkill at this point (as many functions will not work). But a nice future idea

**Comment by tzagim** [comment]
Yes, it turns out that it takes them a long time until they transfer correctly data from the meter...

**Comment by GuyKh** [comment]
Yeah... freaking IEC... :(
