### ISSUE TITLE
fail setup

### ISSUE THREAD

**Issue by hvazana** [GuyKh/iec-custom-component#150]
## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.44-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4976
Installed Version | 1.34.0
Stage | running
Available Repositories | 1464
Downloaded Repositories | 49
HACS Data | ok

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 98.0 GB
disk_used | 32.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Studio Code Server (5.15.0), File editor (5.8.0), AirCast (4.2.1), Terminal & SSH (9.14.0), Mosquitto broker (6.4.1), Google Assistant SDK (2.5.0), Simple Scheduler (2.5), Duck DNS (1.18.0), Node-RED (18.0.5), ESPHome (2024.7.3), Home Assistant Google Drive Backup (0.112.1), eWeLink Smart Home (1.4.3), Spotify Connect (0.13.0), Whatsapp (1.4.0), Grafana (10.0.0), AppDaemon (0.16.6), Plex Media Server (3.5.2), RTSPtoWebRTC (1.0.1), RTSPtoWeb - WebRTC (1.4.0), NGINX Home Assistant SSL proxy (3.10.1), Cloudflared (5.1.17), Zigbee2MQTT (1.39.1-1), TasmoAdmin (0.30.4), MariaDB (2.7.1), phpMyAdmin (0.9.1), ESPresense Companion (0.6.5), Tailscale (0.21.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 30
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 13, 2024 at 6:54 PM
-- | --
current_recorder_run | August 16, 2024 at 10:16 PM
estimated_db_size | 421.56 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 8 / 18
local_online | 6 / 6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Since the last integration update, I can not activate the IEC integration.  downloaded the 0.031 beta version. the integration stuck at  the initiation stage after getting the OTP.

### Reproduction steps

1. upgarded the version to 0.031 beta
2.
3.
...

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.iec.coordinator
Source: helpers/update_coordinator.py:354
integration: Israel Electric Corporation (IEC) (documentation, issues)
First occurred: 10:23:09 PM (12 occurrences)
Last logged: 10:36:26 PM

Unexpected error fetching Iec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 436, in _async_update_data
    last_meter_read = int(devices_by_id.counter_devices[0].last_mr)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

### Diagnostics dump

there is no diagnostic file

**Comment by GuyKh** [comment]
Did you jst moved to a smart meter? Or any recent changes happened?

**Comment by hvazana** [comment]
No.
The smart meter was working already.
The integration worked fine with it

I updated to 2024.8 as I thought it could solve the problem but it did not

**Comment by GuyKh** [comment]
I'll look into it.

**Comment by hvazana** [comment]
Thanks so much

**Comment by GuyKh** [comment]
@hvazana - one last question - are u using a private producer?

**Comment by hvazana** [comment]
No
At least not yet

**Comment by elad-bar** [comment]
Happens also here, started 3 versions ago (~2 weeks)

**Comment by elad-bar** [comment]
@GuyKh don't know if it related, i have solar panels and registered ad such

**Comment by elad-bar** [comment]
One last comment, i'm using v0.0.31-beta

**Comment by GuyKh** [comment]
Everyone with this issue - checkout 0.0.31-beta2 - I added a fallback there

**Comment by hvazana** [comment]
Working perfectly. Thanks.
