### ISSUE TITLE
Potential Collaboration

### ISSUE THREAD

**Issue by matikopi** [GuyKh/iec-custom-component#153]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I thought of a business idea that we can use this api for and I want to discuss wtih you about a potential collaboration.

### Describe the solution you'd like

Send me a message 051-5542110 and we can discuss.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by GuyKh** [comment]
This is not an API - https://github.com/GuyKh/py-iec-api/ is the API.
