### ISSUE TITLE
version 0.0.31 fail to initialize

### ISSUE THREAD

**Issue by Gugulator** [GuyKh/iec-custom-component#154]
## System Information

version | core-2024.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.44-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4627
Installed Version | 1.34.0
Stage | running
Available Repositories | 1391
Downloaded Repositories | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 7.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Mosquitto broker (6.4.1), Home Assistant Google Drive Backup (0.112.1), Zigbee2MQTT (1.39.1-1), Samba share (12.3.2), Network UPS Tools (0.13.1), Vaultwarden (Bitwarden) (0.22.0), Advanced SSH & Web Terminal (18.0.0), RPC Shutdown (2.5), SQLite Web (4.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 17
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 9, 2024 at 21:14
-- | --
current_recorder_run | August 19, 2024 at 21:28
estimated_db_size | 86.76 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Needs attention
IEC Account (my id)
No devices or entities
Failed setup, will retry: cannot access local variable 'last_meter_read' where it is not associated with a value

### Reproduction steps

fresh install of integration.

system details:
Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.0
Frontend 20240809.0

### Debug logs

```text
Logger: custom_components.iec.coordinator
Source: helpers/update_coordinator.py:354
integration: Israel Electric Corporation (IEC)

Unexpected error fetching Iec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 423, in _async_update_data
    total_kva_price, estimated_kwh_consumption = await self._estimate_bill(contract_id, device.device_number,\
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 640, in _estimate_bill
    if not is_private_producer or not last_meter_read:
                                      ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'last_meter_read' where it is not associated with a value
```

**Comment by GuyKh** [comment]
Use `0.0.31-fix`

**Comment by Gugulator** [comment]
> Use `0.0.31-fix`

how to install the fix?

**Comment by GuyKh** [comment]
just install 0.0.32

**Comment by Gugulator** [comment]
ok, manually copied files of 0.31.fix
still getting error in logs:

Logger: custom_components.iec.coordinator
Source: helpers/update_coordinator.py:354
integration: Israel Electric Corporation (IEC) ([documentation](https://github.com/guykh/iec-custom-component), [issues](https://github.com/guykh/iec-custom-component/issues))
First occurred: 22:05:07 (2 occurrences)
Last logged: 22:05:26

Unexpected error fetching Iec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 423, in _async_update_data
    total_kva_price, estimated_kwh_consumption = await self._estimate_bill(contract_id, device.device_number,
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 659, in _estimate_bill
    power_size = await self._get_power_size(connection_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 195, in _get_power_size
    power_size = await self.api.get_power_size(connection_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 527, in get_power_size
    return await static_data.get_power_size(self._session, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/static_data.py", line 126, in get_power_size
    power_size = connection_to_power_size_map[connection]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '25'

**Comment by Gugulator** [comment]
upgraded to 0.0.32
still same error:

Logger: custom_components.iec.coordinator
Source: helpers/update_coordinator.py:354
integration: Israel Electric Corporation (IEC) ([documentation](https://github.com/guykh/iec-custom-component), [issues](https://github.com/guykh/iec-custom-component/issues))
First occurred: 22:07:45 (1 occurrences)
Last logged: 22:07:45

Unexpected error fetching Iec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 423, in _async_update_data
    total_kva_price, estimated_kwh_consumption = await self._estimate_bill(contract_id, device.device_number,
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 659, in _estimate_bill
    power_size = await self._get_power_size(connection_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 195, in _get_power_size
    power_size = await self.api.get_power_size(connection_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 527, in get_power_size
    return await static_data.get_power_size(self._session, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/static_data.py", line 126, in get_power_size
    power_size = connection_to_power_size_map[connection]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '25'

**Comment by Gugulator** [comment]
currently 2 new errors appeared in logs, probably due to some service down on IEC side.

- first one:

Logger: custom_components.iec.coordinator

Source: custom_components/iec/coordinator.py:120
integration: Israel Electric Corporation (IEC) ([documentation](https://github.com/guykh/iec-custom-component), [issues](https://github.com/guykh/iec-custom-component/issues))
First occurred: 22:15:00 (1 occurrences)
Last logged: 22:15:00

Bad logger message: Failed fetching device details by meter id my_clock_id_number ((IECError('(Code 500): Something went wrong please try again!'),))

- second one:

Unexpected error fetching Iec data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 423, in _async_update_data
    total_kva_price, estimated_kwh_consumption = await self._estimate_bill(contract_id, device.device_number,
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 648, in _estimate_bill
    last_meter_read = last_meter_reading.reading
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'reading'

**Comment by tzagim** [comment]
+1

**Comment by GuyKh** [comment]
Install 0.0.30 for now. I'm on a holiday

**Comment by tzagim** [comment]
@GuyKh 
Have a great time on holiday, you might want to pre-release 31 and 32 for now.

**Comment by GuyKh** [comment]
Found the issue for:
```
power_size = connection_to_power_size_map[connection]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '25'
```

https://github.com/GuyKh/py-iec-api/pull/130

**Comment by GuyKh** [comment]
@Gugulator try with `0.0.33` (currently in Pre-Release)

**Comment by GuyKh** [comment]
Closing for now
