### ISSUE TITLE
Getting Config flow could not be loaded: {"message":"Invalid handler specified"} when trying to add the integration

### ISSUE THREAD

**Issue by BrightStar219** [GuyKh/iec-custom-component#165]
### System Health details

Environment: HA v2024.8.3; Docker; Qnap

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Added the integration successfully through HACS.
When I'm trying to add the integration (Settings > Devices > Integrations), I'm getting the above error message.

### Reproduction steps

1. When adding the integration, error message is displayed
2.
3.
...

### Debug logs

```text
I see this in HA logs:
2024-09-22 08:30:47.655 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration iec: No module named 'iec_api'
2024-09-22 08:35:08.337 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration iec: No module named 'iec_api'
```

**Comment by GuyKh** [comment]
```
Error occurred loading flow for integration iec: No module named 'iec_api'
```

This means that it failed downloading the `py-iec-api` from pypi.org.

Try to reinstall from HACS; and restart HA; 
Make sure you have no errors in the logs during this process
