### ISSUE TITLE
Correcting the date in fromDate

### ISSUE THREAD

**Issue by tzagim** [GuyKh/iec-custom-component#197]
Hi, it's me again :)

Enough time has passed since the installation of the smart meter and correct data is still not being received in the add-on.

After checking it seems that date in "fromDate" cannot be the same as "lastInvoiceDate" but should be less than one day before.

PS In the log it seems to make between 2 and 3 calls every time.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue
_____
#### Resolution 3
Request in the current state with resolution 3, the result is:

```json
{
    "lastInvoiceDate":"2024-11-04",
    "fromDate":"2024-11-04", //Tomorrow 
    "resolution":3
}
```

The result is:

```json
{
    "fromDate":"2024-11-02",
    "toDate":"2024-11-03",
    "totalConsumptionForPeriod":0.546,
    "data":
    [
        {
        "status":0,
        "date":"2024-11-02T00:00:00.000000",
        "value":0.546
        }
    ]
}
```

**0.546 and is incorrect and no information about today.**

When the request is made with **Today** date in `fromDate`, the result is:

```json
{
    "lastInvoiceDate":"2024-11-04",
    "fromDate":"2024-11-03", //Today
    "resolution":3
}
```

The result is:

```json
{
    "fromDate":"2024-11-02",
    "toDate":"2024-11-03",
    "totalConsumptionForPeriod":15.453,
    "data":
    [
        {
        "status":1024,
        "date":"2024-11-02T00:00:00.000000",
        "value":11.265
        },
        {
        "status":0,
        "date":"2024-11-03T00:00:00.000000",
        "value":4.188
        }
    ]
}
```

**11.265 is correct and information about today.**

_____
#### Resolution 1

Request in the current state with resolution 1, the result is:

```json
{
    "lastInvoiceDate":"2024-11-03",
    "fromDate":"2024-11-03", //Today 
    "resolution":1
}
```

The result is:

```json
{
    "fromDate":"2024-11-03",
    "toDate":"2024-11-03",
    "data":[]
}
```

**Daily reading for date: 2024-11-03 is missing, calculating manually.**

When the request is made with **Yesterday** date in `fromDate`, the result is:

```json
{
    "lastInvoiceDate":"2024-11-03",
    "fromDate":"2024-11-02", //Yesterday
    "resolution":1
}
```

The result is:

```json
{
    "fromDate":"2024-11-02",
    "toDate":"2024-11-02",
    "data":
    [
        {
            "status":0,
            "date":"2024-11-02T00:00:00.000000",
            "value":0.123
        },
        {
            "status":0,
            "date":"2024-11-02T00:15:00.000000",
            "value":0.321
        },
        {
            "status":0,
            "date":"2024-11-02T00:30:00.000000",
            "value":0.222
        },
        {
            "status":0,
            "date":"2024-11-02T23:45:00.000000",
            "value":0.333
        }
    ]
}
```

**Full information is received.**

I deleted information that does not change to highlight the problem.

**Update**: current dates for the purpose of simplifying understanding

**Comment by GuyKh** [comment]
WDYM "result is true"

**Comment by GuyKh** [comment]
As for the multiple calls - there are many flows and many request "types" and intentions, all because IEC API is freaking dumb and broken.

There's a call I make with **tomorrow** date, just to get the latest meter reading etc.

By running:
```
{   
    "meterSerialNumber": "{{device_id}}",
    "meterCode": "{{device_code}}",
    "lastInvoiceDate": "2024-10-01",
    "fromDate": "2024-10-01",
    "resolution": 1
}
```

I'm getting:
```
...
    "data": [
        {
            "status": 0,
            "date": "2024-10-01T00:00:00.000000",
            "value": 0.172
        }, ...,
        {
            "status": 0,
            "date": "2024-10-01T23:45:00.000000",
            "value": 0.181
        }
```

So you see here that this is not "wrong", atleast not always and perhaps in some specific cases.

You mentioned enough time passed etc; when installing the addon - it starts to load hourly (`resolution=1`) data from 30days back, and tries to load the next day each iteration (every hour) till it catches up with today.

In addition, a hourly call is made to calculate "todays-usage", which is a sensor by itself.
and others.

I suggest you first to checkout what's going on in [IEC site](https://www.iec.co.il) - specifically - usage screen - open Network tab in DevTools and look for calls to `RemoteReadingRange`
Try to play with it to see which values they use.

**Comment by tzagim** [comment]
Note that you make the call on 02-11-2024 with data 01-10-2024, it is also correct for me.
But it is not possible to read the current date (03-11-2024) in the "fromDate" field, it returns an incorrect result.

To check if this is a problem only in my account, check the results in the following data:
```json
{
    "meterSerialNumber": "{{device_id}}",
    "meterCode": "{{device_code}}",
    "lastInvoiceDate":"2024-11-04",
    "fromDate":"2024-11-04",
    "resolution":3
}
````

Compare the results obtained from:
```json
{
    "meterSerialNumber": "{{device_id}}",
    "meterCode": "{{device_code}}",
    "lastInvoiceDate":"2024-11-04",
    "fromDate":"2024-11-03",
    "resolution":3
}
````

I apologize for the errors in the initial message, I edited it many times and some errors happened, I mean of course that it is "correct".

**Comment by GuyKh** [comment]
When using the later one (`2024-11-03`) - I get a "fuller" result.
While with `2024-11-04` i get a bit lower numbers (and excluding 11-03)...

**Comment by tzagim** [comment]
> When using the later one (`2024-11-03`) - I get a "fuller" result. While with `2024-11-04` i get a bit lower numbers (and excluding 11-03)...

You mean it matches the example I showed in my first message?

Today's date is: `2024-11-03` and if you use tomorrow's date (`2024-11-04`) you getting less information?

That's exactly how it is with me, so why this component use tomorrow's date in the field "fromDate"?

In its current state, it fails to get the correct information from the IEC website.

**Comment by GuyKh** [comment]
Note that calls are made in different flows and for different purposes, often as a fallback of other cases.

**Comment by tzagim** [comment]
היי גיא.
אני יודע שאתה אוהב שזה באנגלית, אבל מרגיש לי שמשהו לא עובר טוב בהסבר אז ברשותך אני אכתוב את ההודעה הזו בעברית.

כשאני מבקש את המידע באתר חברת חשמל עם הפרמטרים הללו
```json
{
    "lastInvoiceDate":"2024-11-04",
    "fromDate":"2024-11-04", //Today 
    "resolution":1
}
```
זה מחזיר תוצאה ריקה
```json
{
    "fromDate":"2024-11-03",
    "toDate":"2024-11-03",
    "data":[]
}
```
רק כאשר אני מזין את תאריך יום האתמול, אני מקבל נתונים מלאים על אתמול, בכל מקרה אני לא מקבל נתונים עדכניים על היום הנוכחי בשאילתא המדוברת.
דוגמה לשאילתא שבה מקבלים נתונים:
```json
{
    "lastInvoiceDate":"2024-11-04",
    "fromDate":"2024-11-03", //Yesterday
    "resolution":1
}
```
____________
וכשאני מגיש את השאילתה הבאה:
```json
{
    "lastInvoiceDate":"2024-11-05",
    "fromDate":"2024-11-05", //Tomorrow 
    "resolution":3
}
```
הוא מחזיר מידע שגוי
```json
{
    "fromDate":"2024-11-03",
    "toDate":"2024-11-02",
    "totalConsumptionForPeriod":0.546,
    "data":
    [
        {
        "status":0,
        "date":"2024-11-03T00:00:00.000000",
        "value":0.546
        }
    ]
}
```
וכך גם החיישן מציג לי כאילו צרכתי `0.546` קוט"ש, שזה לא נכון וגם לא הגיוני.

וכאשר אני מגיש את אותה בקשה אבל עם היום הנוכחי אני מקבל את כל המידע, בדוגמה שמובאת בהודעה הראשונה הצריכה האמיתית הייתה `11.265`, דוגמה לשאילתא תקנית:
```json
{
    "lastInvoiceDate":"2024-11-04",
    "fromDate":"2024-11-03", //Today
    "resolution":3
}
```

וזו התוצאה שמתקבלת:
```json
{
    "fromDate":"2024-11-03",
    "toDate":"2024-11-04",
    "totalConsumptionForPeriod":15.453,
    "data":
    [
        {
        "status":1024,
        "date":"2024-11-03T00:00:00.000000",
        "value":11.265
        },
        {
        "status":0,
        "date":"2024-11-04T00:00:00.000000",
        "value":4.188
        }
    ]
}
```

בדקתי את זה עם מספר חשבונות ובכולן תוצאה זהה.
אני מסיק מזה שה-API מוגדר כך שהערך המקסימלי בשדה "fromDate" תלוי ברזולוציה (resolution), כאשר היא 1 הערך המקסימלי הוא התאריך של אתמול וכאשר היא 3 הערך המקסימלי הוא התאריך של היום, בכל מקרה הוא לא יכול לקבל את התאריך של מחר.

לעצם העניין, אם אתה מצליח לקבל את הנתונים הנדרשים עם התאריך של אתמול, אז מדוע לא להשתמש בזה וכך זה יעבוד טוב גם אצלי ואחרים? :)
תודה על כל מה שאתה עושה.

**Comment by GuyKh** [comment]
I switched to use Monthly with today's date for the "Today Usage" sensors. Please confirm with version 0.0.38

**Comment by tzagim** [comment]
Works great.
Thank you!

**Comment by tzagim** [comment]
@GuyKh 
יכול להיות שהוא מבצע קריאות מרובות מכיוון שבכל פעם שלוחצים על "טען מחדש" הוא יוצר לופ חדש?
בכל לחיצה על טעינה מחדש כמות הקריאות הן כמספר הלחיצות.

**Comment by GuyKh** [comment]
No, Multiple calls are for various reasons since many data "sources" needs to be used;
1. For Statistics - it tries to fetch a hourly (resolution=1) reading from it's last read.
2. For Today/Yesterday it does 1/2 calls of Daily (resolution=3)
3. There are fallbacks to fetch data if something is missing from other dates and resolutions.

Take a look at the code and you'll see (cordinator.py)

**Comment by tzagim** [comment]
@GuyKh 
To solve the problem presented above, It seems that the following line also needs to be changed:
https://github.com/GuyKh/iec-custom-component/blob/df39429c71a335653fe179c9d1293eecfb516f0e/custom_components/iec/coordinator.py#L439
```localized_today - timedelta(days=1)```

I changed locally, to solve the problem.

**Comment by GuyKh** [comment]
I'm not 100% sure how fetching yesterday's hourly data solves this

**Comment by tzagim** [comment]
@GuyKh 
```json
{
  "meterSerialNumber":"12345678",
  "meterCode":"123",
  "fromDate":"2024-11-17",
  "resolution":3,
  "lastInvoiceDate":"2024-11-17"
}

{
    "status": 0,
    "futureConsumptionInfo": {
        "currentDate": "2024-11-18",
        "futureConsumption": 10.11,
        "totalImport": 9876.543,
        "totalImportDate": "2024-11-18"
    },
    "fromDate": "2024-11-01",
    "toDate": "2024-11-18",
    "totalConsumptionForPeriod": 123.999,
    "totalImportDateForPeriod": "2024-11-18",
    "meterStartDate": "2024-07-25",
    "totalImport": 9876.543,
    "data": [
        {
            "status": 1024.0,
            "date": "2024-11-01T00:00:00.000000",
            "value": 11.111
        },
        {
            "status": 1024.0,
            "date": "2024-11-02T00:00:00.000000",
            "value": 12.120
        },
        {
            "status": 1024.0,
            "date": "2024-11-03T00:00:00.000000",
            "value": 13.130
        },
        {
            "status": 1024.0,
            "date": "2024-11-04T00:00:00.000000",
            "value": 14.140
        },
        {
            "status": 1024.0,
            "date": "2024-11-05T00:00:00.000000",
            "value": 15.150
        },
        .......
        {
            "status": 1024.0,
            "date": "2024-11-17T00:00:00.000000",
            "value": 10.100
        },
        {
            "status": 0.0,
            "date": "2024-11-18T00:00:00.000000",
            "value": 0.345
        }
    ]
}
```

**Comment by tzagim** [comment]
It turns out that this is not the problem, it suddenly stops receiving information about consumption, and brings incorrect data.
I will monitor for a few days to try to understand where the problem is.

**Comment by tzagim** [comment]
@GuyKh 
Throwing my thoughts here, you have more experience with this than I do.

My problem is that the data is pulled correctly once, and the next day the true data no longer arrives.

Guidelines:
1. If there is no last invoice data (payment through an external company), last invoice is set to the first day of the last month. (hypothesis).
2. when I request tomorrow's data in resolution 3, incorrect data arrives. (fact).
3. I found no difference in results when I set the invoice date to the current month.

I checked the IEC website and they check the monthly (3) as follows:

```json
{
  "meterSerialNumber":"12345678",
  "meterCode":"123",
  "lastInvoiceDate":"2024-10-01",
  "fromDate":"2024-11-01",
  "resolution":3
}
```

Therefore I changed the local code to the following format:
```python
                for device in devices:
                    attributes_to_add[METER_ID_ATTR_NAME] = device.device_number
                    first_day = localized_today.replace(day=1)

                    remote_reading = await self._get_readings(
                        contract_id,
                        device.device_number,
                        device.device_code,
                        first_day,
                        ReadingResolution.MONTHLY,
                    )
```

All that remains is to wait until tomorrow to see what I get :)

**Comment by GuyKh** [comment]
When mentioning wrong/right data - you mean only about current consumption, correct?

**Comment by GuyKh** [comment]
Daily consumption then? (Today's / Yesterday's)?

**Comment by tzagim** [comment]
> Daily consumption then? (Today's / Yesterday's)?

yap.

This morning it was showing incorrect data again, after reloading it pulled correct data.

Without the change it was unable to pull the correct data

**Comment by GuyKh** [comment]
So, once again - I'm trying to get to the bottom line here.
You suggest that due to API problems, when fetching for a Daily (resolution=3) and Today's date - the data returned is wrong.
So - It's better to have Daily data from **Yesterday** (if it includes the same month).

However, you also said that the morning data is still wrong.
This is where I don't follow.

**Comment by tzagim** [comment]
שוב בעברית בכדי שיהיה מהיר וברור.
התובנות עד כה:
1. התאריך לא יכול להיות גבוה מאתמול, התאריך המומלץ הוא הראשון לחודש (כך גם פועלת הקריאה ל-API באתר חברת החשמל).
2. אם התאריך גבוה מאתמול אצלי הוא לא מצליח לקרוא את הנתונים והוא מגדיר את הצריכה היומית על 0.00 ואת הצריכה אתמול על 0.x (למשל 0.132).
3. משום מה בתוסף הוא לא מצליח לקרוא את הנתונים אוטומטית והוא מקבל נתונים שגויים, כאשר מבצעים טעינה מחדש מתקלים נתוני אמת.
4. למרות שמתקבלים נתוני אתמול בלוג מתקבלת שגיאה, אבל הוא מציג את נתוני האמת כפי שמקבלים, בדוגמה המצ"ב 21/11/24 יתקבל 15.123 ועל 22/11/24 יתקבל 0.132 (שזו כבר בעיה בסנכרון של חברת החשמל שהוא לא מצליח להציג נתונים עדכניים):
```json
{
    "status": 0,
    "futureConsumptionInfo": {
        "currentDate": "2024-11-22",
        "futureConsumption": 123.321,
        "totalImport": 9999.999,
        "totalImportDate": "2024-11-22"
    },
    "fromDate": "2024-11-01",
    "toDate": "2024-11-22",
    "totalConsumptionForPeriod": 123.321,
    "totalImportDateForPeriod": "2024-11-22",
    "meterStartDate": "2024-07-25",
    "totalImport": 9999.999,
    "data": [
        {
            "status": 1024.0,
            "date": "2024-11-01T00:00:00.000000",
            "value": 20.220
        },
        {
            "status": 1024.0,
            "date": "2024-11-02T00:00:00.000000",
            "value": 16.160
        },
        .....
        {
            "status": 1024.0,
            "date": "2024-11-21T00:00:00.000000",
            "value": 15.123
        },
        {
            "status": 0.0,
            "date": "2024-11-22T00:00:00.000000",
            "value": 0.132
        }
    ]
}
Daily reading for date: 2024-11-21 is missing, calculating manually
```

**Comment by tzagim** [comment]
לגבי הראשון לחודש, אני רוצה לבדוק כיצד מבוצעת אז הקריאה באתר חברת החשמל, זה ייתן לנו תשובה מהי הדרך הנכונה לקריאה.

לגבי 3, נראה שבאזור חצות הוא מנסה לבצע קריאה ל-API בכדי לקבל את הנתונים המעודכנים, לא ברור לי אם מדובר בתקלה אצלי או בשגיאה של הבקשה (פעם אחת הופיע בלוג שגיאה 500) אבל לא מתקלים נתונים מכונים, כאשר אני לוחץ על טעינה מחדש של התוסף הוא מושך את הנתונים הנכונים.

**Comment by tzagim** [comment]
@GuyKh 
החכמתי עוד קצת בימים שחלפו.
ראשית, יש המון תקלות באחזור נתונים מחברת החשבמל, אבל התקלה היא אצלם (וידאתי מספר פעמים).
שנית, במרבית המקרים לא מצאתי פער משמעותי בין קריאת הראשון לחודש לבין תאריך המחר בבדיקה חודשית (3), היו מקרים בודדים לכאן ומקרים בודדים לכאן, אני עדיין לא סגור סופית מה עדיף.
אבל, מאז בדקתי גם את הראשון לחודש, ושם ההבדל מובהק, ניתן לקבל את המידע רק אם מזינים 1 לחודש הקודם ולא תאריך אחר.
במקרה שלנו:
```json
"fromDate":"2024-11-01"
```

**Comment by tzagim** [comment]
```py
from dateutil.relativedelta import relativedelta

if localized_today.day == 1:
    first_of_the_month = localized_today - relativedelta(months=1, day=1)
else:
    first_of_the_month = localized_today.replace(day=1)
```

**Comment by tzagim** [comment]
כך זה נראה בנתיים אצלי, ופועל תקין.
```py
            if is_smart_meter:
                # For some reason, there are differences between sending 2024-03-01 and sending 2024-03-07 (Today)
                # So instead of sending the 1st day of the month, just sending today date

                devices = await self._get_devices_by_contract_id(contract_id)

                if localized_today.day == 1:
                    first_of_the_month = (localized_today - timedelta(days=1)).replace(day=1)
                else:
                    first_of_the_month = localized_today.replace(day=1)

                for device in devices:
                    attributes_to_add[METER_ID_ATTR_NAME] = device.device_number

                    remote_reading = await self._get_readings(
                        contract_id,
                        device.device_number,
                        device.device_code,
                        first_of_the_month,
                        ReadingResolution.MONTHLY,
                    )
```
נראה ש#228 מיישם את זה.

**Comment by GuyKh** [comment]
תודה על הבדיקה.

אסתכל אצלי שהכל רץ בסדר ואכניס את התיקון.

**Comment by GuyKh** [comment]
@tzagim אתה לא מבין כמה באגים זה הציף אצלי, תראה את כמות השינויים ותבין...

אבל טוב שעולים על זה.
נראה סבבה.

**Comment by GuyKh** [comment]
Changes released in 0.0.43. Please check @tzagim

**Comment by tzagim** [comment]
@GuyKh 

On the first run it works great, I think it manages to pull the information in a shorter time (instead of about 30 seconds + to get all the information).

I will update if there are any changes.

Thank you very much for your excellent work.

**Comment by GuyKh** [comment]
Thank you for the great cooperation, thoughts, exploration and help!

**Comment by tzagim** [comment]
@GuyKh 

אני בכוונה נשאר בשרשור הזה בכדי לא ליצור בלבול.

תקציר, היום מצאתי את המקרה הפוך, שעדיף תאריך של היום או מחר מאשר תאריך של ראשון לחודש. לא מצאתי את הסיבה לתקלה אבל ייתכן שיש קשר לקריאה היומית שמשחרר אותו איכשהו.

ובהרחבה, על פי השינוי החדש הוא מציג את היום הראשון לחודש בכדי לקבל את המידע, להלן הבקשה מתוך הלוג שלי:

```json
{
    "meterSerialNumber": "{{device_id}}",
    "meterCode": "{{device_code}}",
    "fromDate": "2024-12-01",
    "resolution": 3,
    "lastInvoiceDate": "2024-12-01"
}
```
התוצאה שמתקבלת היא צריכה של פחות מקילוואט אחד בתאריך האתמול (3/12/24).
אגב, נראה שהנתון ```lastInvoiceDate``` חסר משמעות לצורך קבלת התוצאה. (כלומר הוא נתון חובה אך כל תאריך שיופיע בו לא ישפיע על התוצאה).

ואילו כאשר אני מגיש את הבקשה עם תאריך של היום או מחר:
```json
{
    "meterSerialNumber": "{{device_id}}",
    "meterCode": "{{device_code}}",
    "lastInvoiceDate": "2024-12-01",
    "fromDate": "2024-12-03",
    "resolution": 3
}
```
מתקבלים נתונים נכונים על הצריכה אתמול.
וזה שונה לחלוטין ממה שהבנתי עד עכשיו.

תוך כדי שאני בודק האם יש קשר לתחילת החודש או משהו כזה, אני מגלה שאם אני מזין את הנתונים כפי שהם מופיעים בלוג (הראשון לעיל) אני פתאום מקבל תגובה תקינה, בדקתי את כל הקריאות ואני רואה שתי פעולות שבוצעו בין הקריאות הרבות הלא תקינות לקריאה עם התוצאה התקינה.
הראשונה:
```json
{
    "meterSerialNumber": "{{device_id}}",
    "meterCode": "{{device_code}}",
    "fromDate": "2024-12-02",
    "resolution": 1,
    "lastInvoiceDate": "{{lastInvoiceDate}}"
}
```
והשניה (סביר להניח שחסרת משמעות, אבל מניח כאן בכדי שאם נחפש בעתיד נדע מה לחפש):
```
https://www.iec.co.il/assets/animations/desktopLottieLoader.json
```

כעת שאני מריץ את הקריאה כפי שהסקריפט מריץ
```json
{
    "meterSerialNumber": "{{device_id}}",
    "meterCode": "{{device_code}}",
    "lastInvoiceDate": "2024-12-04",
    "fromDate": "2024-12-04",
    "resolution": 1
}
```
אני מקבל את התוצאה הבאה:
```json
{
    "status": 0,
    "futureConsumptionInfo": {
        "currentDate": "2024-12-03",
        "totalImport": 9876.543,
        "totalImportDate": "2024-12-04"
    },
    "fromDate": "2024-12-04",
    "toDate": "2024-12-04",
    "totalImportDateForPeriod": "2024-12-04",
    "meterStartDate": "2024-07-25",
    "totalImport": 9876.543,
    "data": []
}
```
ואחרי שבאתר זה השתחרר זה מופיע גם באפליקציה באופן תקין.

ועוד משהו שבשבילו צריך לפתוח בעיה חדשה, מגרסת מערכת הפעלה 14.0 לא ניתן (אצלי) לטעון מחדש את השילוב ללא הפעלה מחדש של Home Assistent.

**Comment by tzagim** [comment]
@GuyKh 
זה יצטרך להמתין ל-12 בלילה או מחר בבוקר.
נראה שברגע שהקריאה מבוצעת פעם אחת, הוא כאילו "משחרר" את ה-API וכל הקריאות הבאות יוצאות תקינות.

**Comment by tzagim** [comment]
לא מצליח לשחזר כנראה לא הייתי בכיוון, אבל היום אני רואה דבר מעניין אחר.
קריאה ראשונה:

```json
{
  "fromDate":"2024-12-01",
  "resolution":3
}
```

תגובה:
```json
{
  "date":"2024-12-04T00:00:00.000000",
  "value":0.088
}
```

קריאה שניה:

```json
{
  "fromDate":"2024-12-05",
  "resolution":3
}
```

תגובה:
```json
{
  "status":1024,
  "date":"2024-12-05T00:00:00.000000",
  "value":12.345
},
{
  "status":0.0,
  "date":"2024-12-05T00:00:00.000000",
  "value":0.321
}
```
המחשבה שיש לי כעת היא, אולי הלוגיקה צריכה להיות לפי הסטטוס, נראה שסטטוס תקין (כלומר נתון מדוייק) הוא 1024, וסטטוס לא תקין הוא 0.
ברמה הפרקטית, בודקים את הראשון לחודש, במידע ומקבלים סטטוס 0 בודקים את היום הנוכחי או היום הבא (שניהם מביאים תוצאה זהה).

**Comment by GuyKh** [comment]
כרגע הגישה היא לנסות תמיד את תחילת החודש (עד כדי היום שלפני = תחילת החודש הקודם). => (אם היום הראשון (ולא יום ראשון) אז לקחת קריאה של השבוע ע"ב אתמול, ואם לא - אז את כל החודש הקודם + את החודש הנוכחי).
אתה עדיין חושב שכדאי להשתמש בקריאה הזאת את הקריאה הזאת?

**Comment by tzagim** [comment]
אני עדיין בלמידה, אבל נראה לי שכדאי להתחיל בגישה הקיימת, לבדוק האם הסטטוס של התאריך של אתמול שווה ל-1024, במידה ולא, להריץ קריאה נוספת עם התאריך של היום.

נשמע לך הגיוני?

**Comment by GuyKh** [comment]
יש כבר עכשיו חלק שמוודא [שקריאות יומיות מהיום קיימות](https://github.com/GuyKh/iec-custom-component/blob/main/custom_components/iec/coordinator.py#L507).

לגבי שאר ההתנהגות, פילטור לפי הסטטוס - אני רק תוהה מה פשר הסטטוסים - האם 1024 אומר לא תקין, או זמני, או לא מלא או מה.
אם זמני - זה עלול להיות נכון, אם 'לא תקין', זה כבר לא בסדר.
רק שאין כל כך את מי לשאול

**Comment by GuyKh** [comment]
א' - כבר היום כמו שכתבתי בלינק - בהכרח מביאים את היום אם חסר (ברזולוציה חודשית).
ב' - לגבי הסטטוס - יש הבדל עצום במשמעות של סטטוס 0 - כלומר, האם זאת תוצאה *חלקית* - אם כן, ארצה להראות אותה כי אנחנו במהלך היום. או האם זו תוצאה *לא נכונה* ואז לא ארצה להראות אותה.

**Comment by tzagim** [comment]
להערכתי 0 הם נתונים *חלקיים* ולא מלאים, אבל לא *שגויים*, אבל זו הערכה בלבד.
אבל, אני לא מדבר על מקרה שמתקבל סטטוס 0 בנתוני היום הנוכחי אלא בנתוני אתמול.
זאת הבקשה:
```json
{
  "fromDate":"2024-12-01",
  "resolution":3
}
```
וזו התגובה:
```json
{
    "data": [
        {
            "status": 1024.0,
            "date": "2024-12-01T00:00:00.000000",
            "value": 20.200
        },
        {
            "status": 1024.0,
            "date": "2024-12-02T00:00:00.000000",
            "value": 19.190
        },
        {
            "status": 1024.0,
            "date": "2024-12-03T00:00:00.000000",
            "value": 18.180
        },
        {
            "status": 0.0,
            "date": "2024-12-04T00:00:00.000000",
            "value": 0.345
        }
    ]
}
```
כלומר שנתוני אתמול (2024-12-04) מופיעים בסטטוס 0, במקרה כזה צריכים להגיש בקשה נוספת באופן הבא:

```json
{
  "fromDate":"2024-12-05",
  "resolution":3
}
```
ואז נקבל את הפלט:
```json
{
    "data": [
        {
            "status": 1024.0,
            "date": "2024-12-01T00:00:00.000000",
            "value": 20.200
        },
        {
            "status": 1024.0,
            "date": "2024-12-02T00:00:00.000000",
            "value": 19.190
        },
        {
            "status": 1024.0,
            "date": "2024-12-03T00:00:00.000000",
            "value": 18.180
        },
        {
            "status": 1024.0,
            "date": "2024-12-04T00:00:00.000000",
            "value": 17.170
        },
        {
            "status": 0.0,
            "date": "2024-12-05T00:00:00.000000",
            "value": 0.345
        }
    ]
}
```
שים לב שסטטוס 0 מופיע על התאריך של היום והתאריך של אתמול מופיע עם סטטוס 1024, כלומר השגנו נתונים נכונים על אתמול.

הערת אגב, באתר חברת החשמל מבקשים את הנתונים מה-API באותה השיטה שהסקריפט בודק כעת, כלומר התאריך הוא הראשון לחודש, ולכן גם הנתונים באתר אינם מדוייקים לעיתים, אבל רשמתי לעצמי את הנתונים שמתקבלים מהתאריך של היום ולמחרת בדקתי באתר החברה וקיבלתי את אותם הנתונים בדיוק.
כלומר זו דרך חליפית לבדוק את נתוני האתמול כאשר הם אינם מתקבלים בדרך המקובלת, השיטות מגבות אחת את השניה אבל אף שיטה לא מביאה *תמיד* את התוצאה הנכונה, ולכן נראה שצריכים לבצע בדיקה ראשונית אם נתוני הראשון לחודש, במידה והם אינם תקינים לבצע בדיקה עם נתונים היום.

ייתכן ובהמשך נגלה מתי (תאריכים, ימים, שעות) שיטה 1 עובדת טוב יותר ומתי שיטה 2, ואז נסתפק בקריאה אחת :) .

אמ;לק, אם הסטטוס של *אתמול* מופיע 0 יש להגיש בקשה חדשה עם התאריך של היום במקום הראשון לחודש, ואז (נכון לידע שהצטבר עד עכשיו נראה ש)נקבל נתונים מדוייקים על אתמול (בסטטוס 1024).

**Comment by GuyKh** [comment]
מה שאתה מתאר הוא להתנות את ההתנהגות לפי הצריכה אתמול.
מה לגבי הצריכה *היום*? לדעתך אפשרי לעבוד עם סטטוס 0?

**Comment by tzagim** [comment]
ולגבי אתמול היה משתנה נוסף שהתבלטתי אם לציין אותו, כעת נראה שהוא בעל משמעות. והוא **שעת הבדיקה**.

נראה שמשעה 15 מתחילים להופיע נתוני אמת על אתמול גם בבדיקה לפי הראשון לחודש...

בכדי לאמת את זה בדקתי את ההיסטוריה מתי הופיע נתוני אמת בסקריפט וזה תמיד בין 15-16.

**Comment by tzagim** [comment]
> מה שאתה מתאר הוא להתנות את ההתנהגות לפי הצריכה אתמול. מה לגבי הצריכה _היום_? לדעתך אפשרי לעבוד עם סטטוס 0?

בעיני הוא נתון חסר משמעות, אבל לא מצאתי בנתיים דרך למשוך נתונים עדכניים לצריכה היומית.

**Comment by GuyKh** [comment]
השאלה המשמעותית לדעתי היא האם *פירוש הסטטוס*.
כלומר, אם זה סטטוס "חלקי" = נכון עד נק' זמן מסויימת אך לא מלא, זה עדיף על כלום ומהווה עובדה "נכונה".
בעוד שאם זה סטטוס "שגוי" או "תקול", אז כלום עדיף עליו.

ללא תשובה על זה - לא חושב שנצליח לתת תשובה משמעותית.
אני כרגע, מניח שזה הראשון - ולכן מתעלם מהסטטוס (כלומר, אם מלא - מעולה, אם חלקי, עדיף על כלום)
