### ISSUE TITLE
As of 0.0.38.2, setup fails, field "data" has invalid value / object has no len

### ISSUE THREAD

**Issue by doron1** [GuyKh/iec-custom-component#211]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1461
Downloaded Repositories | 10

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 916.9 GB
disk_used | 16.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Studio Code Server (5.17.2), Advanced SSH & Web Terminal (19.0.0), ESPHome (2024.10.2), WireGuard (0.10.2), File editor (5.8.0), Scrypted (v0.120.0-jammy-full), chrony (4.0.1), Hikvision Doorbell (3.0.16)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 11
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 27, 2024 at 15:26
-- | --
current_recorder_run | November 6, 2024 at 13:10
estimated_db_size | 290.93 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Integration worked well until now. As of upgrade to 0.0.38.2 (via HACS), would not initialize. Received:
`Failed setup, will retry: Field "data" of type Optional[GetInvoicesBody] in ResponseWithDescriptor has invalid value ('property':{'areaId':'0903','districtId':9} ...`

After many failures, deleted integration altogether, restarted HA, added integration. Now:
`Failed setup, will retry: object of type 'NoneType' has no len()`

### Reproduction steps

1.update to 0.0.38.2 via HACS
2.
3.
...

### Debug logs

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 389, in _async_update_data
    kva_tariff = await self._get_kva_tariff()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iec/coordinator.py", line 189, in _get_kva_tariff
    self._kva_tariff = await self.api.get_kva_tariff()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/iec_client.py", line 511, in get_kva_tariff
    return await static_data.get_kva_tariff(self._session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/static_data.py", line 93, in get_kva_tariff
    await _get_tariffs(session)
  File "/usr/local/lib/python3.12/site-packages/iec_api/static_data.py", line 42, in _get_tariffs
    response = await commons.send_get_request(session=session, url=GET_KWH_TARIFF_URL)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/iec_api/commons.py", line 125, in send_get_request
    parse_error_response(resp, json_resp)
  File "/usr/local/lib/python3.12/site-packages/iec_api/commons.py", line 92, in parse_error_response
    if len(json_resp) > 0:
       ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by GuyKh** [comment]
Try with 0.0.40.2

**Comment by GuyKh** [comment]
Should be fixed with 0.0.40+

**Comment by doron1** [comment]
> Should be fixed with 0.0.40+

Installed 0.0.40.2, deleted entry, restarted HA (to start clean), added new entry. Same behavior as the first time.

![HA-IEC-issue-1](https://github.com/user-attachments/assets/a13ae7d0-cfd4-44b7-8d84-6d137ace5a35)

**Comment by GuyKh** [comment]
@doron1 - please open a separate ticket for that; and add logs

**Comment by doron1** [comment]
> @doron1 - please open a separate ticket for that; and add logs

Not sure why sep ticket for same issue? However, As You Wish

**Comment by GuyKh** [comment]
Is this the same issue?

**Comment by GuyKh** [comment]
If using (iec_api = 0.0.46) - you shouldn't be seeing the same log since:
https://github.com/GuyKh/py-iec-api/blob/main/iec_api/commons.py#L93
the line is:
`    if json_resp and len(json_resp) > 0:`

**Comment by doron1** [comment]
> Is this the same issue?

Looks pretty much the same as the _first one_ mentioned above. I can see the confusion - as described in the issue desc, once I removed the entry completely, restarted HA and added the entry again, the issue changed (to "no len")  and the included log was from this subsequent instance.
However, my initial issue right after installing 0.0.38.2 looked the same as #212 .
