### ISSUE TITLE
IEC integration setup fails

### ISSUE THREAD

**Issue by pshotts** [GuyKh/iec-custom-component#220]
## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | aarch64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4980
Installed Version | 2.0.1
Stage | running
Available Repositories | 1529
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20 December 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | eu-central-1-9.ui.nabu.casa
certificate_status | ready
instance_id | a1404730df0046c0a2bc949771c2c188
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 28.0 GB
disk_used | 9.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | green
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.17.3), Node-RED (18.1.1), Terminal & SSH (9.15.0), Samba share (12.3.2), Home Assistant Google Drive Backup (0.112.1), Music Assistant Server (2.3.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 9
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31 October 2024 at 06:34
-- | --
current_recorder_run | 10 November 2024 at 14:31
estimated_db_size | 123.54 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration fails to setup.
It had been working well for me for several months.
I have enabled debug logging of the integration.
Then I restarted HA and the setup failed.
I then deleted my setup, and re-installed, getting a new code from IEC in the process.
Setup still fails

### Reproduction steps

1.
2.
3.
...
Then I restarted HA and the setup failed.
I then deleted my setup, and re-installed, getting a new code from IEC in the process.
Setup still fails

### Debug logs

```text
https://drive.google.com/file/d/1mfD3PAFQZhpDN_qLZoWh6npwuzT1pbwM/view?usp=drive_link
```

### Diagnostics dump

Not available

**Comment by GuyKh** [comment]
Sent access request

**Comment by pshotts** [comment]
Access granted

**Comment by GuyKh** [comment]
@pshotts - it seems you're using **not the latest version**.

Please verify it with the latest version

**Comment by pshotts** [comment]
Thank you!
I don't understand how I didn't get notification of an update, but never mind.
All is working again, so I am closing the issue as resolved.
@GuyKh Thank you for all your work on this and on the 2 IMS integrations that I am using all the time!
