### ISSUE TITLE
Failed setup, will retry: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by r0ma007** [GuyKh/iec-custom-component#226]
## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4993
Installed Version | 2.0.1
Stage | running
Available Repositories | 1471
Downloaded Repositories | 63

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 1, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | eu-central-1-22.ui.nabu.casa
certificate_status | ready
instance_id | 84707140cb5942839bb5e56ccf2a189a
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 23.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 29
views | 26
mode | storage

</details>

<details><summary>MiWifi</summary>

version | 3.0.0
-- | --
192.168.1.1 (xiaomi.router.ra69) | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 10, 2024 at 19:03
-- | --
current_recorder_run | November 12, 2024 at 19:24
estimated_db_size | 171.94 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.22
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 19

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

![image](https://github.com/user-attachments/assets/7fa44782-054a-477e-9bcd-510b47058ddd)

### Reproduction steps

1.--------------
2.
3.
...

### Debug logs

```text
--------------
```

**Comment by GuyKh** [comment]
Please check for update and verify with latest version
