### ISSUE TITLE
Keep getting 401 errors

### ISSUE THREAD

**Issue by tsvi** [GuyKh/iec-custom-component#229]
## System Information

version | core-2024.12.0b4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.62-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1474
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0.rc2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 234.0 GB
disk_used | 83.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.112.1), MariaDB (2.7.1), Mosquitto broker (6.4.1), Nginx Proxy Manager (1.0.1), Samba share (12.3.2), File editor (5.8.0), UniFi Network Application (3.5.0), Duck DNS (1.18.0), Studio Code Server (5.17.3), Glances (0.21.1), Transmission (4.0.6), ESPHome Device Compiler (2024.11.2), Spotify Connect (0.13.0), TeslaMate (0.22.0), PostgreSQL (1.0.0), Whisper (2.2.0), Piper (1.5.2), Whatsapp (1.4.1), Network UPS Tools (0.13.2), Grafana (10.2.2), Frigate (0.14.1), Photoprism (ubuntu-2024-09-15), Cloudflared (5.2.2), Music Assistant Server (2.3.3), Jellyfin NAS (10.10.3), Advanced SSH & Web Terminal (19.0.0), Nextcloud (30.0.2-test), Duplicati add-on (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 10
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 20, 2024 at 22:01
-- | --
current_recorder_run | December 2, 2024 at 22:12
estimated_db_size | 3622.62 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/GuyKh/iec-custom-component/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I keep getting 401 errors on the IEC integration.
I tried removing and adding back my account, but I keep getting the following error:
This error originated from a custom integration.

Logger: custom_components.iec.coordinator
Source: custom_components/iec/coordinator.py:274
integration: Israel Electric Corporation (IEC) (documentation, issues)
First occurred: 22:15:17 (1 occurrences)
Last logged: 22:15:17

Bad logger message: Failed fetching reading for Contract: xxxxxxxx,date: 02-12-2024, resolution: 3 ((IECError('(Code 401): Contract is not associated with you.'),))

### Reproduction steps

1. Removed the integration, added it back. Failed
2. Restarted. Failed
3. no other ideas...
...

### Debug logs

```text
andlers.py", line 1493, in emit
    self.enqueue(self.prepare(record))
                 ~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/handlers.py", line 1475, in prepare
    msg = self.format(record)
  File "/usr/local/lib/python3.13/logging/__init__.py", line 998, in format
    return fmt.format(record)
           ~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 711, in format
    record.message = record.getMessage()
                     ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 400, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/iec/coordinator.py", line 653, in _insert_statistics
    devices = await self._get_devices_by_contract_id(contract_id)
  File "/config/custom_components/iec/coordinator.py", line 128, in _get_devices_by_contract_id
    _LOGGER.exception(
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1554, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1548, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1664, in _log
    self.handle(record)
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1680, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1736, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 41, in handle
    self.emit(record)
Message: 'Failed fetching devices by contract 342484316'
Arguments: (IECError('(Code 401): Contract is not associated with you.'),)
[33m2024-12-02 22:25:23.732 WARNING (MainThread) [iec_api.commons] Failed call: (Code 401): Unauthorized[0m
[31m2024-12-02 22:25:23.734 ERROR (MainThread) [custom_components.iec.coordinator] Failed fetching devices for IEC Contract 342484316[0m
```

**Comment by GuyKh** [comment]
This returns from IEC. I'll look further tomorrow, but perhaps they changed something in their API

**Comment by GuyKh** [comment]
@tsvi - Can you check again.
I saw these errors yesterday, but now it's gone.
Perhaps it's a hickup on IEC side.

**Comment by tsvi** [comment]
Looks like its working now 🤷‍♂️

**Comment by GuyKh** [comment]
Thank IEC :/
