### ISSUE TITLE
support solar production

### ISSUE THREAD

**Issue by ohadlevy** [GuyKh/iec-custom-component#54]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I have a solar system connected to the smart meter

### Describe the solution you'd like

 it would be nice if we can show usage and production for the similar time frames. thank you :)

### Describe alternatives you've considered

na

### Additional context

na

**Comment by GuyKh** [comment]
@ohadlevy That's a great idea.
Any idea if this sort of data exists on IEC website?

**Comment by GuyKh** [comment]
@ohadlevy - can you contact me on guykhmel@gmail.com for more questions?

**Comment by GuyKh** [comment]
For visibility - it seems that in such cases - there are more than a single device per contract.
Need to think how to aggregate the data (or even if)

**Comment by GuyKh** [comment]
Update: from what I could tell, with the help of people, there's no API for exposing PV (Photo Voltaic) meters in the meters.
I'd love some help with Solar/PV to query various APIs in IEC site to try to find this details, but at this point, there's nothing to be done here.

Closing the ticket

**Comment by GuyKh** [comment]
Update: from what I could tell, with the help of people, there's no API for exposing PV (Photo Voltaic) meters in the meters.
I'd love some help with Solar/PV to query various APIs in IEC site to try to find this details, but at this point, there's nothing to be done here.

Closing the ticket
