### ISSUE TITLE
Add support for 'Last Payment Date'

### ISSUE THREAD

**Issue by Suleiman700** [GuyKh/iec-custom-component#57]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not a problem

### Describe the solution you'd like

Adding support for showing 'Last Payment Date' would be great

![image](https://github.com/GuyKh/iec-custom-component/assets/25286081/9cb839a7-a295-4550-a78a-ed5fbb409dcd)

### Describe alternatives you've considered

Not a problem

### Additional context

Not a problem

**Comment by GuyKh** [comment]
Released in `0.0.20` - closing
