### ISSUE TITLE
Get the Current unpaid electricity bill

### ISSUE THREAD

**Issue by benji1703** [GuyKh/iec-custom-component#62]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not a problem

### Describe the solution you'd like

Adding support the 
(currentKWHReading - lastPaidKWH) * tariff 
In order to see what is the current bill status 

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by GuyKh** [comment]
You don't need a sensor for this. Create your own TemplateSensor:

```
template:
  - sensor:
      - name: "Current Unpaid Electric Balance"
        unit_of_measurement: "₪"
        state: >
          {% set last_read = states('sensor.iec_latest_meter_reading') | float %}
          {% set bill_read = states('sensor.last_iec_bill_meter_reading') | float %}
          {% set tariff = states('sensor.iec_kwh_tariff') | float %}

          {{ ((last_read - bill_read) * tariff) | round(2, default=0) }}
```

**Comment by benji1703** [comment]
Indeed, this is possible to get that from a template - but since this is coming back from the API or this could be calculated - I though that this should be a nice to have feature.

**Comment by GuyKh** [comment]
@benji1703, in my perspective, this is somewhat a duplication of data - I don't see a main reason for the component to include this.

A valid idea would be to add this example to the readme as a nice-to-have idea
