### ISSUE TITLE
Missing Icon on integrations page

### ISSUE THREAD

**Issue by EyalRotem** [GuyKh/iec-custom-component#64]
## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.16-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4882
Installed Version | 1.34.0
Stage | running
Available Repositories | 1403
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 22, 2024 at 03:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | ui.nabu.casa
certificate_status | ready
instance_id | *******************
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 62.3 GB
disk_used | 49.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.10.0), File editor (5.8.0), Studio Code Server (5.15.0), ESPHome (2024.2.2), Samba share (12.3.1), Home Assistant Google Drive Backup (0.112.1), HyperHDR (19.0.0.0), Mosquitto broker (6.4.0), MariaDB (2.6.1), MQTT Explorer (browser-1.0.1), Zigbee2MQTT (1.36.0-1), AC MQTT proxy for home assistant (0.6.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 7
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 13, 2023 at 06:38
-- | --
current_recorder_run | March 12, 2024 at 16:03
estimated_db_size | 9636.97 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Nothing major, just the icon missing on the integrations page
![image](https://github.com/GuyKh/iec-custom-component/assets/12516268/bab60d57-53e1-46a9-b31c-459013a92e71)

tested on 2 local PCs and 2 phones

### Reproduction steps

1. install
2. view integrations page

### Debug logs

```text
none needed really.
```

**Comment by GuyKh** [comment]
Wayyyyy ahead of you :) - a PR is open for HA brands:
https://github.com/home-assistant/brands/pull/5254
