### ISSUE TITLE
Expose  device instead of a list of entities

### ISSUE THREAD

**Issue by sefininio** [GuyKh/iec-custom-component#88]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/iec/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When adding the entities to a dashboard, we have to add them one by one. 

### Describe the solution you'd like

Exposing as a device will allow to add them all with a single click:
<img width="385" alt="image" src="https://github.com/GuyKh/iec-custom-component/assets/7566666/8e565d40-5e88-420d-b853-a8006d1866c8">
as well as see all scripts/scenes/automations they take part in.

### Describe alternatives you've considered

adding them one by one :(

### Additional context

.

**Comment by GuyKh** [comment]
I'll check this out 👍🏻
